sonar.projectKey=customer-support-system
sonar.organization=Pentiente
sonar.projectName=Customer Support System
sonar.sources=.
sonar.exclusions=**/venv/**, **/tests/**, **/__pycache__**, setup.cfg
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml