# Identificadores del Proyecto (Deben coincidir con los creados en SonarQube)
sonar.projectKey=customer-support-system
sonar.projectName=Customer Support System
sonar.projectVersion=1.0.0

# Configuración de Rutas
sonar.sources=Implementaci-n-de-Calidad-a-Customer-Support
sonar.tests=tests
sonar.python.version=3.10

# Exclusiones (No analizar código que no es nuestro o configuración)
sonar.exclusions=**/venv/**, **/__pycache__**, **/*.xml, setup.cfg, requirements.txt

# Integración con Reporte de Cobertura
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8