name: Calidad y Pruebas (CI)

# Se ejecuta en cada push a cualquier rama (para que detecte la tuya)
on:
  push:
    branches:
      - '**' #El ** significa "todas las ramas"
  pull_request:
    branches:
      - '**'

jobs:
  quality-check:
    name: Análisis de Calidad
    runs-on: ubuntu-latest

    steps:
      # 1. Bajar el código del repositorio
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Importante para el análisis histórico

      # 2. Preparar Python
      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Instalar dependencias
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4. Análisis Estático (Flake8)
      - name: Correr Flake8
        run: |
          # Detener si hay errores graves
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Reportar complejidad y estilo (sin detener el build por ahora)
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      # --- NUEVO PASO DE DEBUG ---
      - name: Debug - Listar archivos (¿Dónde estás carpeta tests?)
        run: |
          echo "📂 Listando archivos en la raíz:"
          ls -la
          echo "📂 Buscando carpeta tests:"
          find . -name "tests" -type d
          echo "📂 Buscando carpeta Tests (Mayúscula):"
          find . -name "Tests" -type 

      # 5. Ejecutar Pruebas y Generar Cobertura (XML)
      - name: Ejecutar Pytest con Cobertura
        run: |
          # 1. indica que busque la carpeta
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          
          # 2. Ejecutamos las pruebas (apuntando explícitamente a la carpeta tests/)
          pytest tests/ --cov=src --cov-report=xml --cov-report=term
          
      # 6. Escaneo de SonarQube (LOCAL con Ngrok)
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 